package com.minsbot.agent.tools;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Resume / modify / extend a previously-generated project. Reads the persisted
 * history in {@link ProjectHistoryService} so the agent can pick up where a
 * past session left off — even across bot restarts.
 */
@Component
public class ContinueProjectTools {

    private static final Logger log = LoggerFactory.getLogger(ContinueProjectTools.class);

    private final ProjectHistoryService history;
    private final ClaudeCodeTools claudeCodeTools;

    public ContinueProjectTools(ProjectHistoryService history, ClaudeCodeTools claudeCodeTools) {
        this.history = history;
        this.claudeCodeTools = claudeCodeTools;
    }

    @Tool(description = "List all projects previously generated by this bot. "
            + "Use when the user asks 'what projects have I made?', 'show my projects', "
            + "'where is my X project?', or as a lookup before calling continueProject. "
            + "Returns project name, folder path, GitHub URL, and when it was created.")
    public String listMyProjects() {
        List<ProjectHistoryService.ProjectRecord> recs = history.list();
        if (recs.isEmpty()) return "No projects in history yet.";
        StringBuilder sb = new StringBuilder("Your generated projects (most recent first):\n");
        int i = 1;
        for (ProjectHistoryService.ProjectRecord r : recs) {
            sb.append(i++).append(". ").append(nz(r.projectName, "(unnamed)"));
            sb.append("\n   Folder: ").append(nz(r.workingDir, "?"));
            if (r.githubUrl != null) sb.append("\n   GitHub: ").append(r.githubUrl);
            sb.append("\n   Mode: ").append(nz(r.mode, "?"))
              .append(" | Status: ").append(nz(r.status, "?"))
              .append(" | When: ").append(nz(r.completedAt, "?"));
            sb.append("\n");
            if (i > 20) break; // keep output reasonable for the LLM
        }
        return sb.toString();
    }

    @Tool(description = "Continue/resume/modify a previously-generated project. "
            + "MUST be called when the user says 'continue <name> project', 'work on <name>', "
            + "'add <feature> to <name>', 'modify the <name> project', 'resume <name>'. "
            + "Looks up the project's saved folder path, then delegates to Claude Code CLI "
            + "inside that folder so it can read existing files and make incremental changes. "
            + "Do NOT use createCodeWithClaude for continuation — it would scaffold from scratch.")
    public String continueProject(
            @ToolParam(description = "Project name or fuzzy match (e.g. 'rich-app', 'house-shopping')") String projectName,
            @ToolParam(description = "What to do next on the project — a feature to add, a bug to fix, "
                    + "or 'continue working on it' if the user didn't specify") String change) {
        if (projectName == null || projectName.isBlank()) {
            return "Error: project name is required. Call listMyProjects first to see available names.";
        }
        ProjectHistoryService.ProjectRecord rec = history.findByName(projectName);
        if (rec == null) {
            // History is empty or has no match. Rather than blindly scanning the
            // filesystem (which hits the PowerShell approval gate and is slow),
            // ASK THE USER for the path using clickable choice buttons.
            return "I don't have '" + projectName + "' in my project history. "
                    + "Where is it?\n\n"
                    + "Please reply with the full folder path, e.g.:\n"
                    + "  C:\\Users\\cholo\\eclipse-workspace\\" + projectName + "\n\n"
                    + "Or choose:\n\n"
                    + "[Create a new " + projectName + " project instead - Enter]\n"
                    + "[Skip, I'll handle it myself]";
        }
        Path dir = Path.of(rec.workingDir);
        if (!Files.isDirectory(dir)) {
            return "Project '" + rec.projectName + "' was recorded at " + rec.workingDir
                    + " but that folder no longer exists. The project may have been deleted or moved.";
        }

        String work = (change == null || change.isBlank())
                ? "Continue working on this project. Review the current state, pick the most "
                + "useful next thing to implement (a missing feature, a TODO, a rough edge), "
                + "and implement it cleanly."
                : change.trim();

        String prompt =
                "⚠ NON-INTERACTIVE MODE. The user is NOT watching and CANNOT answer follow-up questions. "
                + "Asking 'what changes would you like me to implement?' is a FAILURE — there is nobody to answer.\n\n"
                + "Existing project location: " + rec.workingDir + "\n\n"
                + "Your job: make real code changes on disk to satisfy the following request.\n\n"
                + "REQUEST:\n" + work + "\n\n"
                + "RULES:\n"
                + "1. Read the existing project first (pom.xml, package.json, README, source tree).\n"
                + "2. Do NOT scaffold a new project or overwrite everything. Modify in place.\n"
                + "3. If parts of the request are ALREADY satisfied (stack already matches, framework already there), "
                + "SKIP those parts and do what's still missing. Example: if user says 'convert to Spring Boot + Tailwind' "
                + "and it's already Spring Boot, just ADD Tailwind CSS integration, a sample Tailwind-styled page, and wire it up.\n"
                + "4. If the request is ambiguous, pick the most reasonable interpretation and IMPLEMENT IT. "
                + "Do not ask for clarification — there is no one to clarify with.\n"
                + "5. Success = new or modified files exist AND the project still compiles. "
                + "Silence or a question is a failure; you must produce file changes.\n"
                + "6. Commit with a clear message when done. If tests exist, run them.\n"
                + "7. Do NOT start a long-running dev server (mvn spring-boot:run, npm run dev, etc). "
                + "The user has a separate mechanism for that.";

        log.info("[ContinueProject] project={} dir={} change={}", rec.projectName, dir,
                work.length() > 120 ? work.substring(0, 120) + "..." : work);
        // Snapshot file set BEFORE running so we can detect "Claude wrote nothing".
        java.util.Set<String> before = snapshotFiles(dir);
        String out = claudeCodeTools.run(prompt, rec.workingDir, false, false);
        java.util.Set<String> after = snapshotFiles(dir);

        // Punt detection: Claude responded but made no actual file changes AND its
        // output reads like a summary/plan ("Summary", "To run", "Solution Options",
        // "what would you like"). Replace the output with clickable choices so the
        // user isn't stuck staring at a verbose "here's what you could do" reply.
        boolean nothingChanged = before.size() == after.size() && before.containsAll(after);
        if (nothingChanged && looksLikePunt(out)) {
            log.info("[ContinueProject] Detected punt — offering clickable choices for '{}'", rec.projectName);
            return buildPuntChoices(rec);
        }
        return "Continuing project '" + rec.projectName + "' at " + rec.workingDir
                + (rec.githubUrl != null ? " (GitHub: " + rec.githubUrl + ")" : "")
                + "\n\n" + out;
    }

    private java.util.Set<String> snapshotFiles(java.nio.file.Path dir) {
        java.util.Set<String> out = new java.util.HashSet<>();
        if (dir == null || !java.nio.file.Files.isDirectory(dir)) return out;
        java.util.Set<String> skip = java.util.Set.of(".git", "target", "build", "dist", "out",
                "node_modules", ".gradle", ".idea", ".vscode", "__pycache__", "venv");
        try (var s = java.nio.file.Files.walk(dir)) {
            s.filter(java.nio.file.Files::isRegularFile).forEach(pp -> {
                for (java.nio.file.Path part : dir.relativize(pp)) {
                    if (skip.contains(part.toString())) return;
                }
                out.add(dir.relativize(pp).toString().replace('\\', '/'));
            });
        } catch (Exception ignored) {}
        return out;
    }

    /** Classic Claude punt markers: summary-of-what-exists + "to run" + asks for clarification. */
    private static boolean looksLikePunt(String out) {
        if (out == null) return false;
        String lower = out.toLowerCase();
        int signals = 0;
        if (lower.contains("## summary") || lower.contains("**summary")) signals++;
        if (lower.contains("to run") || lower.contains("**to run the")) signals++;
        if (lower.contains("solution options") || lower.contains("what changes would you like")
                || lower.contains("what would you like me to")) signals++;
        if (lower.contains("available endpoints") || lower.contains("configuration:")) signals++;
        return signals >= 2;
    }

    private static String buildPuntChoices(ProjectHistoryService.ProjectRecord rec) {
        String name = rec.projectName;
        return "Claude analyzed **" + name + "** but didn't modify anything — the request was too open-ended for a definitive edit. Pick a concrete direction:\n\n"
                + "[Add Tailwind CDN homepage at /]\n"
                + "[Add Thymeleaf + Tailwind template at /]\n"
                + "[Just run it as-is]\n"
                + "[Cancel - Enter]";
    }

    private static String nz(String s, String fallback) {
        return (s == null || s.isBlank()) ? fallback : s;
    }
}
